import type { ClientType } from '@/types/client.types'

export interface ClientRow {
  id: string
  initials: string
  name: string
  contactName: string
  contactEmail: string
  type: ClientType
  projects: number
  jobs: number
  outstanding: number
  invoiceLabel: string
  status: 'Active' | 'Inactive'
}

export const MOCK_CLIENTS: ClientRow[] = [
  {
    id: '1',
    initials: 'ABC',
    name: 'ABC Corporation',
    contactName: 'Michael Brown',
    contactEmail: 'michael@abccorp.com',
    type: 'Commercial',
    projects: 3,
    jobs: 12,
    outstanding: 18450,
    invoiceLabel: '2 invoices',
    status: 'Active',
  },
  {
    id: '2',
    initials: 'KS',
    name: 'Karthik Subramanian',
    contactName: 'Cameron Williamson',
    contactEmail: 'felicia.reid@example.com',
    type: 'Residential',
    projects: 1,
    jobs: 4,
    outstanding: 0,
    invoiceLabel: 'Up to date',
    status: 'Active',
  },
  {
    id: '3',
    initials: 'GB',
    name: 'Green Building Co',
    contactName: 'Kristin Watson',
    contactEmail: 'nathan.roberts@example.com',
    type: 'Commercial',
    projects: 5,
    jobs: 18,
    outstanding: 24650,
    invoiceLabel: '3 invoices',
    status: 'Active',
  },
  {
    id: '4',
    initials: 'BD',
    name: 'Beats by Dre',
    contactName: 'Guy Hawkins',
    contactEmail: 'curtis.weaver@example.com',
    type: 'Commercial',
    projects: 2,
    jobs: 7,
    outstanding: 0,
    invoiceLabel: 'Up to date',
    status: 'Active',
  },
  {
    id: '5',
    initials: 'BA',
    name: 'BMW Australia Ltd',
    contactName: 'Guy Hawkins',
    contactEmail: 'curtis.weaver@example.com',
    type: 'Commercial',
    projects: 2,
    jobs: 7,
    outstanding: 0,
    invoiceLabel: 'Up to date',
    status: 'Active',
  },
  {
    id: '6',
    initials: 'NA',
    name: 'Nasa of America',
    contactName: 'Guy Hawkins',
    contactEmail: 'curtis.weaver@example.com',
    type: 'Commercial',
    projects: 2,
    jobs: 7,
    outstanding: 0,
    invoiceLabel: 'Up to date',
    status: 'Active',
  },
  {
    id: '7',
    initials: 'PH',
    name: 'Power Housing Ltd',
    contactName: 'Michael Brown',
    contactEmail: 'michael@abccorp.com',
    type: 'Commercial',
    projects: 3,
    jobs: 12,
    outstanding: 12400,
    invoiceLabel: '5 invoices',
    status: 'Active',
  },
  {
    id: '8',
    initials: 'AB',
    name: 'ABC Corporation',
    contactName: 'Michael Brown',
    contactEmail: 'michael@abccorp.com',
    type: 'Commercial',
    projects: 3,
    jobs: 12,
    outstanding: 6000,
    invoiceLabel: '3 invoices',
    status: 'Active',
  },
  {
    id: '9',
    initials: 'RN',
    name: 'Rafael Nascimento',
    contactName: 'Michael Brown',
    contactEmail: 'michael@abccorp.com',
    type: 'Residential',
    projects: 3,
    jobs: 12,
    outstanding: 8250,
    invoiceLabel: '7 invoices',
    status: 'Active',
  },
  {
    id: '10',
    initials: 'KY',
    name: 'Kelven Yao',
    contactName: 'Michael Brown',
    contactEmail: 'michael@abccorp.com',
    type: 'Residential',
    projects: 3,
    jobs: 12,
    outstanding: 950,
    invoiceLabel: '1 invoices',
    status: 'Active',
  },
]
